# Generated by Django 3.2.5 on 2021-07-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('idteam', models.AutoField(db_column='idTeam', primary_key=True, serialize=False)),
                ('teamname', models.CharField(db_column='TeamName', max_length=100)),
                ('firstfantacoach', models.CharField(db_column='FirstFantaCoach', max_length=100)),
                ('secondfantacoach', models.CharField(blank=True, db_column='SecondFantaCoach', max_length=45, null=True)),
                ('crediti', models.CharField(db_column='Crediti', max_length=45)),
            ],
            options={
                'verbose_name': 'Teams',
                'db_table': 'Teams',
                'managed': False,
            },
        ),
    ]
