# Generated by Django 3.2.5 on 2021-07-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('idcoach', models.AutoField(db_column='idCoach', primary_key=True, serialize=False)),
                ('rank', models.CharField(db_column='Rank', max_length=45)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
