# Generated by Django 3.2.5 on 2021-07-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('idleague', models.AutoField(db_column='idLeague', primary_key=True, serialize=False)),
                ('leaguename', models.CharField(db_column='LeagueName', max_length=100)),
                ('teamnumber', models.CharField(db_column='TeamNumber', max_length=45)),
                ('password', models.CharField(db_column='Password', max_length=128)),
                ('crediti', models.CharField(db_column='Crediti', max_length=45)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'db_table': 'Leagues',
                'managed': False,
            },
        ),
    ]
